name: outfitofTheDay
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^4.2.0
  path: ^1.9.0
  path_provider: ^2.1.4

  receive_sharing_intent: ^1.5.3
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  cloud_functions: ^4.7.6

  # Ostatné
  google_sign_in: ^6.3.0
  http: ^1.2.1
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  geolocator: ^12.0.0
  dio: ^5.9.0
  table_calendar: ^3.0.9

  # Lokalizácia
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/mannequins/
    - assets/hero/